apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: dev
spec:
  scaleTargetRef:
    name: leitura-dev

  minReplicaCount: 1
  maxReplicaCount: 3

  triggers:
  - type: rabbitmq

    metadata:
      protocol: http # Optional. Specifies protocol to use, either amqp or http, or auto to autodetect based on the `host` value. Default value is auto.
      queueName: "dev-messages"

      mode: QueueLength # QueueLength or MessageRate
      value: "20" # message backlog or publish/sec. target per instance

    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn
