#cronjob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: escrita-cronjob

spec:
  schedule: "* * * * *" # A cada minuto, ou tb, */1 * * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: escrita
            image: guilhermeperes/ms-escrita:latest
          restartPolicy: OnFailure
