apiVersion: batch/v1beta1
kind: CronJob
namespace: ms
metadata:
  name: escrita-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: escrita
            image: guilhermeperes/ms-escrita:latest
          restartPolicy: OnFailure
