apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ms

resources:
- deployment-leitura.yaml
- deployment-escrita.yaml
- scaledobject.yaml
- service-leitura.yaml
- service-escrita.yaml