# dev/escrita/dev-configmap-escrita
apiVersion: v1
kind: ConfigMap

metadata:
  name: escrita-config
  namespace: ms

data:
  APP_NAME: "dev-app-escrita"
  RABBITMQ_QUEUE: "dev-messages"
  TIMER: "1"
  RABBITMQ_PORT: "5672"            # 5672 
