# dev/escrita/dev-secret-escrita
apiVersion: v1
kind: Secret
metadata:
  name: escrita-secret
  # namespace: ms
type: Opaque
data:
  # RABBITMQ_URL: bG9jYWxob3N0Cg==     # localhost
  # RABBITMQ_URL: cmFiYml0bXEtY2x1c3Rlci5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs    # NOME do SERVICE do RabbitMQ
  # RABBITMQ_PORT: 5672            # 5672 
  # RABBITMQ_USERNAME: Z3Vlc3Q=        # user 
  # RABBITMQ_PASSWORD: Z3Vlc3Q=    # password