# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secret.yaml
- auth.yaml

# - escrita/cronjob.yaml
# - escrita/deployment.yaml
# - escrita/service.yaml

# - leitura/deployment.yaml
# - leitura/scaledobject.yaml
# - leitura/service.yaml