# Como estou usando o mesmo URL, USERNAME E PASS
# fiz esse arquivo unico que vai servir para todas aplicações.
# Caso seja diferente, teria que criar arquivos secret.yaml
# nas diferentes pastas. ex: 
# dev/escrita/secret.yaml
# prod/leitura/secret.yaml
# Alem de mudar os nomes, namespaces e referencia-los
# corretamente no arquivo de Deployment

apiVersion: v1
kind: Secret
metadata:
  name: conn-secret

type: Opaque
data:
  # BASE 64 ENCODED
  
  # Se aplicações rodam no mesmo namespace entao coloca o nome do serviço
  # Se forem em namespaces diferentes coloca o ip do serviço
  RABBITMQ_URL: "MTAuOTkuNzkuODA="      # 10.99.79.80
  RABBITMQ_USERNAME: "dXNlcg=="         # user 
  RABBITMQ_PASSWORD: "cGFzc3dvcmQ="     # password


  host: aHR0cDovL3VzZXI6cGFzc3dvcmRAMTAuOTkuNzkuODA6MTU2NzIv # http://user:password@10.99.79.80:15672/
