# deployment-rabbitmq.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq-deployment
  namespace: ms

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:latest
          ports:
            - containerPort: 5672  # Porta para acesso ao RabbitMQ
            - containerPort: 15672 # Porta para acesso ao painel de controle do RabbitMQ
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
            - name: RABBIT_PORT
              value: "5672"