#deployment-escrita.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: escrita
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: escrita
  template:
    metadata:
      labels:
        app: escrita
    spec:
      containers:
        - name: escrita-container
          image: guilhermeperes/ms-escrita:latest
          envFrom:
            - configMapRef:
                name: escrita-config
            - secretRef:
                name: escrita-secret