apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: wordpress
          image: docker.io/bitnami/wordpress:6.1.1-debian-11-r23
          env:
            - name: AVANTI_ENV_VALUE
              value: "development"
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-dev
