apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../bases/

namespace: development

commonLabels:
  kustomize-source: development
  environment: development
  owner-team: ied-avanti

commonAnnotations:
  avanti.io/source: https://github.com/avanti/poc-wordpress
  avanti.io/branch: development

resources:
- dev-namespace.yaml

patches:
- target:
    kind: Deployment
    name: wordpress
  path: dev-deploy-wordpress.yaml
- target:
    kind: PersistentVolumeClaim
    name: wordpress
  patch: |-
    - op: replace
      path: /metadata/name
      value: wordpress-dev
    - op: replace
      path: /spec/resources/requests/storage
      value: 3Gi
- target:
    kind: Secret
    name: wordpress-mariadb
  path: dev-secret-wordpress-mariadb.yaml
- target:
    kind: Secret
    name: wordpress
  path: dev-secret-wordpress.yaml
- target:
    kind: StatefulSet
    name: wordpress-mariadb
  path: dev-sts-wordpress-mariadb.yaml
- target:
    kind: Service
    name: wordpress
  patch: |-
    - op: add
      path: /spec/externalIPs
      value: [ "172.26.28.36" ]
    - op: replace
      path: /spec/ports/0/port
      value: 7089
    - op: replace
      path: /spec/ports/1/port
      value: 7443