# dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-app

resources:
- ../base

configMapGenerator:
  - name: escrita-config
    files:
    - escrita/configmap.yaml

secretGenerator:
  - name: escrita-secret
    files:
    - escrita/secret.yaml

