apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/version: 10.6.11
    app.kubernetes.io/managed-by: kustomize
    app: wordpress
    k8s-app: mariadb
    environment: production
type: Opaque
stringData:
  mariadb-root-password: "AAAAgApOkmHF+dWybNQpP+TV"
  mariadb-password: "AAAAHaQubQ+o/N8GU3jdP+Rk"
