kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/version: 6.1.1
    app.kubernetes.io/managed-by: kustomize
    app: wordpress
    k8s-app: wordpress
    environment: prodution
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
