apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/version: 6.1.1
    app.kubernetes.io/managed-by: kustomize
    app: wordpress
    k8s-app: wordpress
    environment: prodution
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: wordpress
    k8s-app: wordpress
