apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/version: 10.6.11
    app.kubernetes.io/managed-by: kustomize
    app: wordpress
    k8s-app: mariadb
    environment: prodution
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
      k8s-app: mariadb
  serviceName: wordpress-mariadb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: 9ac062f7dfb1de282f2df5193b988d82179e17290964aad97ad39db3998aafd5
      labels:
        app: wordpress
        k8s-app: mariadb
    spec:
      #serviceAccountName: wordpress-mariadb
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: wordpress
                    k8s-app: mariadb
                topologyKey: kubernetes.io/hostname
              weight: 1
      initContainers:
        - name: mariadb-fix-permission
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
          command:
            - /bin/sh
          args:
            - -c
            - |
              /bin/chmod -R '777' /bitnami/mariadb
              /bin/chown -R 1001.99 /bitnami/mariadb
              ls -l  /bitnami/mariadb
              ls -l /bitnami/mariadb
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
      containers:
        - name: mariadb
          image: docker.io/bitnami/mariadb:10.6.11-debian-11-r12
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            #Container does not have user 1001 and group 99
            #runAsUser: 0
            #runAsGroup: 0
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: mariadb-root-password
            - name: MARIADB_USER
              value: "bn_wordpress"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mariadb
                  key: mariadb-password
            - name: MARIADB_DATABASE
              value: "bitnami_wordpress"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          resources: 
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
            - name: config
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: wordpress-mariadb
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
              app: wordpress
              k8s-app: mariadb
              environment: prodution
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "2Gi"
