apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: "default"
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/version: 6.1.1
    app.kubernetes.io/managed-by: kustomize
    app: wordpress
    k8s-app: wordpress
    environment: production
type: Opaque
stringData:
  wordpress-password: "AAAAdUlwOVdXbFhtNg=="
