apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  kustomize-source: base
  environment: testing
  owner-team: ied-avanti

commonAnnotations:
  avanti.io/source: "https://github.com/avanti/poc-wordpress"

resources:
- base-cm-wordpress-mariadb.yaml
- base-deploy-wordpress.yaml
- base-pvc-wordpress.yaml
- base-secret-wordpress-mariadb.yaml
- base-secret-wordpress.yaml
- base-sts-wordpress-mariadb.yaml
- base-svc-wordpress-mariadb.yaml
- base-svc-wordpress.yaml