# prod/leitura/deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: leitura-prod
  namespace: prod

spec:
  replicas: 1
  selector:
    matchLabels:
      app: leitura-prod
  template:
    metadata:
      labels:
        app: leitura-prod
    spec:
      containers:
        - name: leitura-prod
          image: guilhermeperes/ms-leitura:latest
          env:
          # ConfigMap
          - name: RABBITMQ_PREFETCH
            valueFrom:
              configMapKeyRef:
                name: leitura-config-prod
                key: RABBITMQ_PREFETCH
          - name: RABBITMQ_QUEUE
            valueFrom:
              configMapKeyRef:
                name: leitura-config-prod
                key: RABBITMQ_QUEUE
          # Secrets
          - name: RABBITMQ_URL
            valueFrom:
              secretKeyRef:
                name: conn-secret
                key: RABBITMQ_URL
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: conn-secret
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: conn-secret
                key: RABBITMQ_PASSWORD
         



                